### ISSUE TITLE
Add continuous integration configuration

### ISSUE THREAD

**Issue by rumyantseva** [rumyantseva/go-velobike#10]
It might be helpful to compile library and run examples every time when code changes.

So, looks like we need to add Travis CI configuration here, yeah.

**Comment by jainnidhi703** [comment]
I want to work on it.

**Comment by rumyantseva** [comment]
@jainnidhi703 thank you! Please, feel free to do it. If you have any questions, you can ask here.

**Comment by duckoder** [comment]
@jainnidhi703 @rumyantseva hello guys. I have a question, how you want to setup CI without tests ? :)

**Comment by rumyantseva** [comment]
@zhikiri tests are necessary, yeah (if you would like to help with tests, you are welcome). But right now we have at least examples here: https://github.com/rumyantseva/go-velobike/tree/master/examples.
So, first of all at least we may check what it's possible to compile library code and examples code ;-)

**Comment by duckoder** [comment]
@rumyantseva ou, okay. So for now you want just run compile and run example, understood. @jainnidhi703 was first and already started to working on issue, so best wishes :)

**Comment by rumyantseva** [comment]
@zhikiri yeah, right :) 

Kirill, if you have any ideas about the tests, please, feel free to create an issue. I can give few examples of JSON responses from the real server (from my user).

**Comment by riktimmondal** [comment]
i am sending a PR

**Comment by rumyantseva** [comment]
@riktimmondal unfortunately, your PR doesn't solve the problem. btw, @jainnidhi703 was first and probably already started working on the issue.

**Comment by rumyantseva** [comment]
solved in #12
