### ISSUE TITLE
Dealing with Time fields

### ISSUE THREAD

**Issue by rumyantseva** [rumyantseva/go-velobike#5]
Response bodies contain some fields related with time. For example, `StartDate` and `Duration`. Right now we handle these fields as strings but for the next major version it's better to parse this data to `time.Time` type.

**Comment by gunjan01** [comment]
@rumyantseva  I would like to help on this :)

**Comment by rumyantseva** [comment]
@gunjan01 yeah, thanks! Go on! If you have any questions or need examples, feel free to ask. And happy hacktoberfest! :)

**Comment by gunjan01** [comment]
Yes. Will ping you :). Happy hacktoberfest to you too! 💃

**Comment by gunjan01** [comment]
@rumyantseva  Do we need to add relevant tests for the responses too ?

**Comment by rumyantseva** [comment]
@gunjan01 well... if you have time that would be nice to add them (maybe in a separated PR)
thanks! :)

**Comment by gunjan01** [comment]
@rumyantseva Sent the PR. Please review it ! :)
